### ISSUE TITLE
Documentation / Example

### ISSUE THREAD

**Issue by dustinfarris** [csantero/ember-sinon#1]
First, thanks for doing this.

Second, can you add an example of using sinon in an ember-cli test?  I'm not sure I'm doing it right.

**Comment by lolmaus** [comment]
I second that.

**Comment by dustinfarris** [comment]
FYI, we are using sinon for our adapter addon tests.

Here's how we are using it: https://github.com/dustinfarris/ember-django-adapter/blob/master/tests/unit/serializers/drf-test.js

**Comment by lolmaus** [comment]
@dustinfarris, thank you for sharing, but this file does not help. You already have `sinon` available globally there.

Is installing this plugin enough for `sinon` to become available?

**Comment by csantero** [comment]
@lolmaus Installing this plugin and running the blueprint should give access to sinon in the global namespace from your tests.

**Comment by lolmaus** [comment]
@csantero, oh, okay then!

I've looked into the blueprint and noticed that it unconditionally adds Sinon. Doesn't this mean that Sinon will be also bundled in production?

**Comment by csantero** [comment]
@lolmaus No, check out `index.js`. The tree does indeed get added to the ember pipeline, but the `app.import` statement to actually include the file in your assets directory is only executed if in test mode.

**Comment by lolmaus** [comment]
@csantero, ok, but what about running tests with livereloading via `ember s` and `http://localhost:4200/tests`? It's considered to be a `development` environment and the `/index.js` only mentions `test`.

I'm sorry for asking instead of trying it out myself. I already have Sinon installed manually and i'm trying to figure out whether it's worth removing it in favor of `ember install:addon ember-sinon`.

**Comment by csantero** [comment]
@lolmaus It does indeed work in the development tests environment. The `test: true` flag I'm passing to `app.import` tells Ember CLI to bundle it in `test-support.js` instead of `vendor.js`. `test-support.js` is loaded when visiting `/tests`, as well as when running `ember test`, so sinon will be present in both environments. This is the same approach used by ember-cli-qunit.

**Comment by csantero** [comment]
@dustinfarris Sorry I missed this topic originally. Sadly I don't have much time to devote to this project at the moment, but pull requests are welcome!

**Comment by dustinfarris** [comment]
@csantero No worries!  We figured it out—and it's been working really well for us.  Thanks again for this addon.

**Comment by lolmaus** [comment]
> @csantero 
> @lolmaus It does indeed work in the development tests environment. The test: true flag I'm passing to app.import tells Ember CLI to bundle it in test-support.js instead of vendor.js. test-support.js is loaded when visiting /tests, as well as when running ember test, so sinon will be present in both environments. > > This is the same approach used by ember-cli-qunit.

This is awesome! You should totally put this info into the readme.
