### ISSUE TITLE
ember-cli-blanket spits an error: Could not find module `ember-sinon/acceptance-tests/sinon` imported from `exam-sim-ember/acceptance-tests/sinon`

### ISSUE THREAD

**Issue by lolmaus** [csantero/ember-sinon#20]
Got both ember-cli-blanket and ember-sinon in my project.

Blanket complains in browser console during tests:

> Error: Could not find module `ember-sinon/acceptance-tests/sinon` imported from `exam-sim-ember/acceptance-tests/sinon`

**Comment by csantero** [comment]
Could you possible make a demo repo?

**Comment by mitchlloyd** [comment]
Just a note that I have a similar problem with https://github.com/mitchlloyd/ember-autosave at commit 570d0c2cc5b9121abfae53dbaf63f5f92e4086b5.

**Comment by lolmaus** [comment]
It's as simple as:

```
ember new blah
cd blah
ember install ember-cli-blanket
ember install ember-sinon
ember s
```

Then go to http://localhost:4200/tests/ , enable coverage and look into the console.

**Comment by csantero** [comment]
After trying this out, it appears that although the error message does show up, it doesn't seem to impact the running of the tests in any way - sinon can still be imported just fine, and blanket is still generating coverage results. Since the message is being generated from blanket, maybe you could try opening up an issue over on ember-cli-blanket.

**Comment by lolmaus** [comment]
Roger. Will reopen if necessary.
