### ISSUE TITLE
Move sinon-qunit support into separate addon

### ISSUE THREAD

**Issue by csantero** [csantero/ember-sinon#26]

**Comment by elwayman02** [comment]
@csantero here you go:

[Ember-Sinon-QUnit](http://jhawk.co/ember-sinon-qunit)

This addon doesn't do exactly what Sinon-QUnit does...the main issue being that Ember-QUnit wraps the QUnit tests differently and the Sinon sandboxing from sinon-qunit (or the shim in ember-sinon) wasn't working as a result due to loss of context. You should now be able to remove the sinon shim from this addon.

**Comment by elwayman02** [comment]
Ember-Sinon-QUnit's blueprint installs Ember-Sinon as well, fyi, so there is no need to `ember install` them both separately.
